print("perform leonie/init.lua")

require("leonie.basic")
require("leonie.colorscheme")
require("leonie.diagnostics")
require("leonie.packer")
require("leonie.mason")
require("leonie.code_handling")
require("leonie.lsp.rust")
require("leonie.code_completion")
require("leonie.neotree")
require("leonie.markdown-preview")
require("leonie.lualine")
