print("perform leonie/init.lua")

require("leonie.basic")
require("leonie.colorscheme")
require("leonie.diagnostics")
require("leonie.code_handling")
require("leonie.window-remap")
require("leonie.terminal")
require("leonie.tig")
require("leonie.undotree")
require("leonie.lsp.lua")
require("leonie.lsp.rust")
require("leonie.lsp.slint")
require("leonie.lsp.typst")

require("leonie.config.lazy")
